# Generated by Django 4.0.3 on 2022-03-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('no_hp', models.CharField(max_length=12)),
            ],
        ),
    ]
